# Generated by Django 5.0.1 on 2024-01-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('deposit_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('deposit_date', models.DateField()),
                ('referral_id', models.IntegerField()),
                ('status', models.CharField(choices=[('HOLDING', 'Holding'), ('PAID_BACK', 'Paid back')], default='HOLDING', max_length=50)),
                ('paid_back_date', models.DateField(null=True)),
                ('return_referral_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('room_nr', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
