# Generated by Django 5.0.1 on 2024-01-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0002_deposit_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter',
            name='deposit_id',
        ),
        migrations.RemoveField(
            model_name='renter',
            name='rental_id',
        ),
        migrations.AddField(
            model_name='renter',
            name='deposit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='renting.deposit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renter',
            name='rental',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='renting.rental'),
            preserve_default=False,
        ),
    ]
