# Generated by Django 5.0.1 on 2024-01-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0004_renter_renter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='amount',
            new_name='deposit_amount',
        ),
    ]
