# Generated by Django 5.0.1 on 2024-04-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0005_rename_amount_deposit_deposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('HOLDING', 'Holding'), ('PAID_BACK', 'Paid back'), ('PARTIAL_PAID_BACK', 'Partial paid back'), ('COVERED_RENT', 'Covered rent')], default='HOLDING', max_length=50),
        ),
    ]
