# Generated by Django 5.0.1 on 2024-04-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0006_alter_deposit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='referral_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
