# Generated by Django 5.0.1 on 2024-03-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankentry',
            name='entryreference_id',
            field=models.CharField(default=12345, max_length=32),
            preserve_default=False,
        ),
    ]
