# Generated by Django 5.0.1 on 2024-04-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_expectedexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedexpense',
            name='contract_end_date',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expectedexpense',
            name='contract_start_date',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
    ]
