# Generated by Django 5.0.1 on 2024-04-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_expectedexpense_contract_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expectedexpense',
            old_name='entryreference_id',
            new_name='reference',
        ),
    ]
