# Generated by Django 5.0.1 on 2024-04-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_rename_contract_end_date_expectedexpense_billing_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=32)),
                ('source_account', models.CharField(max_length=32)),
                ('destination_account', models.CharField(max_length=32)),
                ('dc', models.CharField(max_length=1)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=5, max_digits=15)),
                ('memo', models.TextField()),
            ],
        ),
    ]
