# Generated by Django 5.0.1 on 2024-04-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_internaltransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternalTransaction',
        ),
        migrations.AddField(
            model_name='bankentry',
            name='type',
            field=models.CharField(choices=[('rent', 'Rent'), ('internal_transaction', 'Internal Transaction'), ('expense', 'Expense')], default='Rent', max_length=32, null=True),
        ),
    ]
