# Generated by Django 5.0.1 on 2024-04-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_delete_internaltransaction_bankentry_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankentry',
            old_name='reference',
            new_name='referral_id',
        ),
        migrations.AlterField(
            model_name='bankentry',
            name='type',
            field=models.CharField(choices=[('rent', 'Rent'), ('deposit', 'Deposit'), ('internal_transaction', 'Internal Transaction'), ('expense', 'Expense')], default='Rent', max_length=32, null=True),
        ),
    ]
