# Generated by Django 5.0.1 on 2024-04-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_rename_reference_bankentry_referral_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankentry',
            old_name='entryreference_id',
            new_name='entryreferral_id',
        ),
        migrations.RenameField(
            model_name='expectedexpense',
            old_name='reference',
            new_name='referral_id',
        ),
    ]
