# Generated by Django 5.0.1 on 2024-04-22 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_alter_bankentry_type_revenuereport'),
        ('renting', '0007_alter_deposit_referral_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenuereport',
            old_name='bankentry_id',
            new_name='bankentry',
        ),
        migrations.RemoveField(
            model_name='revenuereport',
            name='deposit_id',
        ),
        migrations.AddField(
            model_name='revenuereport',
            name='deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='renting.deposit'),
        ),
    ]
